[theme]
primaryColor        = "#66a7e8"   # teal — buttons, sliders, checkboxes
backgroundColor     = "#34363b"   # light blue-white — main background
secondaryBackgroundColor = "#111e2b"  # slightly darker — sidebar, expanders
textColor           = "#ffffff"   # navy — body text
font                = "sans serif"
